### ISSUE TITLE
Reading serial data from COM3 not working

### ISSUE THREAD

**Issue by iamblesson** [dwilches/Ardity#10]
Hi,
I am using this to read and write data to my Unity application from COM3. 
While i can write the data (a & z strings), i'm unable to read any data that i receive from the COM port. 
I've tried the DemoScene_AutoPoll,  DemoScene_UserPoll_JustRead, DemoScene_UserPoll_ReadWrite. 
Either one of these scene won't show the message received from the COM port in the console window.
Any reason why? Anything i may be missing?

Thanks.

**Comment by dwilches** [comment]
Hi
Are you using the `Sample Arduino Program` together with the `DemoScene_AutoPoll`?
Did you modify any of them? Which Arduino are you using?

**Comment by iamblesson** [comment]
Hi,
Apologies.
I was communicating with a Crestron Controller.
I forgot to add a \x0D and \x0A (carriage return and line feed)at the end of the string i sent from the controller.
I added these hex values to the string i'm sending from the controller to the COM port and it works perfectly.

Thanks.
