### ISSUE TITLE
Doesn't seem to work in Unity 5.6.0f3?

### ISSUE THREAD

**Issue by doomtoo** [dwilches/Ardity#11]
I tried this out in Unity, but it doesn't seem to be able to receive serial data on the current version.  It can open the connection, see when the serial port is being used by something else, but can't seem to receive data. 

I'm not sure if Unity changed something, the project has to be setup special or something wrong with my computer.

I can get serial output in the arduino IDE, in processing 3, but for some reason, even every demo from every forum posted in the last 7yrs, won't receive any data from the serial port. (besides acknowledging it is opened, which does block other applications from using it- so it can open/ block it, but can't read it).

I'm sure this does work in an older version of Unity- but can you tell me which one?

**Comment by dwilches** [comment]
Hello

I'd bet on it being a difference in the expected format of the messages exchanged between the device and this library. Which format do your messages use, are they delimited by a line-feed, a `\0`, are they prefixed with their length?

If you want to try the same Unity version I have, it's `Unity 5.6.0`.

Could you give me more information about your current setup?

- Which version of Unity are you using?
- Which editor? 32bits or 64bits?
- Which COM port number does you device use? COM1, COM8?
- Which is the format of your messages? this part is very important as 1 byte makes the difference.

**Comment by doomtoo** [comment]
Thanks! 
I was hoping it was a bug with the newer version of Unity, but seems to be an issue with the Arduino 101 board, but not sure what. Trying it out with an Arduino Uno R3, everything works as expected. 

I'm using Unity 5.6.0f3, 64 bit editor (VS2017), COM8 on one computer, COM9 on another.

From the arduino IDE I'm just using the Serial.println command to output to serial.

So it must be an issue somehow with how the 101 outputs serial vs. normal Uno. Weird that the arduino IDE can compensate, and 'processing 3' can as well, but whatever .Net library can't :/ (trying even very simple C# programs outside of Unity even doesn't work).

Thanks for trying to help, and letting me know your Unity version. If you have any ideas, let me know, but it's obviously not an issue with this library- works great with the Uno :/

**Comment by doomtoo** [comment]
Thanks for the help! Once I found it was arduino 101 specific, I was able to find the answer. 
For some reason the 101 needs extra stuff set on the port:
serialPort.DtrEnable = true;
serialPort.RtsEnable = true;
(from:  https://forum.arduino.cc/index.php?topic=467421.0).

Thanks for the help again!
