### ISSUE TITLE
System.IO.Ports is not available in Unity 2018 .net 4.x 

### ISSUE THREAD

**Issue by banezaklan** [dwilches/Ardity#16]
It seems that the System.IO.Ports is not available in Unity 2018. (2018.3.0f2)
I have Player settings->Scripting Runtime Version set to ".NET 4.x or equivalent" and Api Compatibility Level set to .NET 4.x.
I tried changing Api Compatiblity level to ".NET Standard 2.0" which is the only other option available, and I get the same error in the script. 
Has anybody had this problem and fixed it? Any ideas?

**Comment by lluisgl7** [comment]
Hi! I'm using Unity 2018.1.2f1 and it's working for me with no problems. I'm using ".NET 4x Equivalent" Scripting Runtime Version and ".NET 4.x" Api Compatibility Level.

**Comment by banezaklan** [comment]
I resolved the problem by adding a System.IO.dll through Visual Studio.
Project->Add reference->Browse
and then selected from file system:
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.IO.dll

It started to compile without a problem after that. Hope this helps somebody...

**Comment by dwilches** [comment]
Glad it's fixed now. I'll add this information to the README, surely it's of use to others.
