### ISSUE TITLE
Can ardity be used with Bluetooth modules connected to an Arduino

### ISSUE THREAD

**Issue by jasimmj** [dwilches/Ardity#18]
Modules like HC-05 which would essentially have serial ports for communication. can ardity be used for complete wireless control of a device(mobile robot, arduino powered) from unity? Thank you.
I am doing a project on wireless gesture control of a robot using mixed reality(VR+AR).

**Comment by dwilches** [comment]
Hello,
If you can configure your device to appear as a COM port in your machine, then Ardity can connect to it.
So I suggest you first check with a program like PuTTY if you can connect to your device, once you know the adequate baud rate and COM port number, you can pass those parameters to Ardity.
Greetings.

**Comment by dwilches** [comment]
Hello,
Is your issue solved?
