### ISSUE TITLE
“returnBuffer” missing from 40 to 39

### ISSUE THREAD

**Issue by NakedVane** [dwilches/Ardity#20]
Your code is cool, data has received safty. But I find a problem with my program. I've lost 1byte in receiving message.

Your code(class,SerialThreadBinaryDelimited):
` 
        byte[] returnBuffer = new byte[index];
        System.Array.Copy(buffer, returnBuffer, index);
`

After I've changed. I had received all the data:

` 
       byte[] returnBuffer = new byte[index +1];
        System.Array.Copy(buffer, returnBuffer, index +1);
`

I need receive hexadecimal 40 bytes from comm, but recived 39 bytes. I've got all the message after I changed above code. Is it a problem?

**Comment by dwilches** [comment]
Hello,

In your mesasage, the byte you were missing was the delimiter byte, is that right?
The original code was written to not return the delimiter byte, but if you want it, then the change you did is the correct fix.

If you were missing a different byte (not the delimiter) then, can you show me a sample message from your command?

Regards.

**Comment by NakedVane** [comment]
Er.....Everything good with orther samples so far. Thank you!
