### ISSUE TITLE
No console data

### ISSUE THREAD

**Issue by Technorocker** [dwilches/Ardity#21]
I have been scratching my head how to connect my IMU sensor through arduino into Unity. I actually got a cube rotating from my own coding but it is very lagged and doesn't respond very well. I just found your Ardity unity asset and am following your manual to get it up and running. So at first I kept my Arduino code the same cause I have it setup to combine the x,y,z into a string and I know it works cause I can get the cube working. I'm more concverned about the multithreading which is what brought me here. 

So I have everything setup properly and when I press play nothing happens. No console logs show up. Not even the connection log shows. I'm not sure what I'm missing. I am using Unity 2018.3.7f1 if that makes a difference. I setup the cube, added the serialController to it. than created the MyMessageListener Script and added it to the serial controller like in the manual and added the controller game object to message listener spot. So from as far as I can tell everything is setup correctly.

I then tried to upload the sample code in the mabnual to test the basics . In the serial monitor of Arduino I can send the A or Z char and it does indeed reply back the correct response. I'm not sure If need to add a temp Serial.Write function to send out the A or Z using the sample arduino code. Any help would be great as I've been fumbling around trying to get my sensor data to properly rotate a cube for a few weeks now. I am pretty new to unity(about a year of unity) and even newer to arduino(Although I know the arduino is sending the data i need)

**Comment by Technorocker** [comment]
I'm sorry, you can delete this issue completely. I was working on the initial sending data issues with my Arduino board in Unity and had turned off the Console logs except errors at the time. I have this up and running and very responsive. Thank you so much for your unity Asset :)

**Comment by dwilches** [comment]
Cool! Glad you found the solution!
