### ISSUE TITLE
Communicate with mblock over COM

### ISSUE THREAD

**Issue by enemali** [dwilches/Ardity#22]
i asked on unity forum but as i'm not an expert i couldn't implement the reply given. 
i have a software that send messages ( code ) to COM2 , COM3 etc . what i want now is to get unity receive those messages on windows 10.
the software that broadcast the messages is [mblock ](http://www.mblock.cc/mblock-software/) which is use in programming the mbot arduino robotic kit.
i want to create an emulator for the mbot in unity which will be programmed from [mblock ](http://www.mblock.cc/mblock-software/).
someone did a similar thing here using [mblock ](http://www.mblock.cc/mblock-software/) and [Vrep ](http://www.coppeliarobotics.com/) and [Virtual Serial Ports Emulator](http://www.eterlogic.com/Products.VSPE.html)
Can i achieved this with this package?

**Comment by dwilches** [comment]
Can you share a link to the Unity Forum question to see what they answered?

From what I'm understanding, what you want is to send messages from mblock to Unity, in mblock's own format. If it's so: out-of-the-box Ardity allows you to receive certain kinds of messages (delimited by new-line for example), but if mblock uses a kind of message that is not supported by Ardity, then you'll need to extend Ardity's capabilities by writing some custom code yourself.

Ardity's code is not too long, so there shouldn't be problem getting to know it and extending it.

**Comment by enemali** [comment]
> Can you share a link to the Unity Forum question to see what they answered?
https://forum.unity.com/threads/unity-receive-message-from-virtual-serial-port.670249/

**Comment by dwilches** [comment]
What they answered in that post is to use the SerialPort class of .Net, that's what Ardity uses.
So, if you can figure out the protocol that mblock uses, then you can use a modified version of Ardity, or you can do it from scratch with the SerialPort class.
