### ISSUE TITLE
change behaviour on build

### ISSUE THREAD

**Issue by DarioScocco** [dwilches/Ardity#28]
Hi, 
 Thanks for share this great library! I am using Ardity for sending data from an IMU connected to an Aduino nano to UNITY. On editor mode it works great receiving aroud 30 meesages for second on updating the animation ok. When I build the program it only get 1 massage every 3-5 seconds and then when I return to edit mode, without changing any configuration,  the message listener continue receiving  massages every 3-5 seconds! I have to return to a previous version of the application before build in order to work again. The serial monitor o Arduino development console show that arduino is sending the messages without changes. 
I dont know what could be hapening!
Thanks

**Comment by DarioScocco** [comment]
Sorry,
I figure it out! An example class was consuming the messages queue, so messages were lost.
Thanks
D

**Comment by dwilches** [comment]
Good to know it's solved now!
