### ISSUE TITLE
OSX no connection when using IL2CPP

### ISSUE THREAD

**Issue by Cross22** [dwilches/Ardity#29]
On OSX 10.14.6, Ardity works fine for me when using Mono, but switching Player Settings to IL2CPP prevents it from connecting. In other words, OnConnectionEvent is never called.

Below is the code I am using to find the connected serial port.
`using System.IO.Ports;
        // Search through all potential ports until we find a USB one
        string[] arrPorts = SerialPort.GetPortNames();

        foreach (string portName in arrPorts)
        {
            if (portName.Contains("usbmodem"))
            {
                controller.portName = portName;
                controller.baudRate = 115200;
                controller.messageListener = this.gameObject;
                controller.gameObject.SetActive(true);
                break;
            }
        }`

**Comment by dwilches** [comment]
Did you find the solution to your issue?
(I don't have an OSX machine where to try to see if I get the same issue.)
