### ISSUE TITLE
Sending strings instead of characters

### ISSUE THREAD

**Issue by twhalen08** [dwilches/Ardity#3]
Hello! 

First off i just want to start by saying Thank you for this. It has helped me understand using serial devices within unity a lot better. 

I need to send a comma separated string over serial to the arduino so that I can then break it down and load it into an array. I can't seem to get a string over to the arduino. I can only send a single character. 
Is sending an entire string instead of a character possible? If so, would you possibly be able to show me an example?

Any help would be much appreciated. 

Tom

**Comment by dwilches** [comment]
Hi!

You are welcome :). It is good to hear this project is being useful out there.

This library can send any string over to the Arduino, just as the one you mentioned. 
The problem you describe sounds like you are using the `Serial.read()` function in your Arduino code, which only reads the first byte sent (if you call it a second time you would get the second character sent).
If you want to read a full string, check the function [Serial.readString()](https://www.arduino.cc/en/Serial/ReadString), that will read the whole string sent. Then you can use the function `toCharArray()` to copy it to a normal C-like string and break it by commas using `strtok()`.

**Comment by twhalen08** [comment]
Thank you! I appreciate the assistance!

**Comment by dwilches** [comment]
You are welcome!

Please note I modified a bit my answer, do not use `c_str()` with `strtok()` because `strtok` modifies the first argument (i.e. the string returned by `c_str`), which is something the Arduino docs tell us not to do.

Better use `toCharArray()` that copies the string to a different char array that you can modify with `strtok` as you want.
