### ISSUE TITLE
reading from sensor to unity3d

### ISSUE THREAD

**Issue by arju68** [dwilches/Ardity#34]
want to read position and force value from sensor into unity3d. Attaching the arduino println commands. How to change to read that values using your plugin. Thanks.
![serialMonitor](https://user-images.githubusercontent.com/58091381/69461472-9c814c00-0d9c-11ea-8224-c171d022ce1b.PNG)

**Comment by dwilches** [comment]
Hello,

There are some examples for communicating Arduino and Unity using Ardity here: [Samples](https://github.com/dwilches/Ardity/tree/master/UnityProject/Assets/Ardity/Scripts/Samples)

A quick place to start is also the section "What do I need to do in Unity?" in [this page](http://ardity.dwilches.com/).

If you have already tried a solution, can you elaborate on how it's not working?

Regards.
