### ISSUE TITLE
Clear Serial port incoming buffer

### ISSUE THREAD

**Issue by Nakin72** [dwilches/Ardity#35]
How to clear buffer for disable messages - Queue is full. Dropping message?

**Comment by dwilches** [comment]
Hello,

The `SerialController` has an input called `Drop Old Message` that you can use. This input does this:

> When the queue is full, prefer dropping the first message in the queue instead of the new message. 
> Use this if you only need the latest message from the port.

You will still see the message `Queue is full. Dropping message: ..` but the queue will accept the new messages.

Regards.
