### ISSUE TITLE
Does Ardity work on Mac?

### ISSUE THREAD

**Issue by jonsulkow** [dwilches/Ardity#37]
my port name looks like this:
/dev/cu.usbmodem144201

This is the error i get: 
Exception: No such file or directory StackTrace:   at System.IO.Ports.SerialPortStream.ThrowIOException () [0x0000f] in ...

**Comment by dwilches** [comment]
Hello,

Yes, Ardity works in Mac. You'll need to find the right port name though. I don't know if `/dev/cu.usbmodem144201` is a good port name in Mac.

One way you can troubleshoot this, is by downloading PuTTY, which can also connect to COM ports, then you can try different names there until you find the right one: https://www.ssh.com/ssh/putty/mac

Regards.
