### ISSUE TITLE
Queue is full.  Dropping message:

### ISSUE THREAD

**Issue by Dirk611** [dwilches/Ardity#38]
Greetings! Kudos on Ardity!  I'm a kinetic artist and really excited about interactive art with Unity! I'm a Unity newbie, as well as C# (two strikes? (o:) but lots of Arduino/ESP32/Parallax Propeller experience.
I've set up your examples and comms to my Arduino are working (getting msgs displayed in Unity console) but it looks like they are only getting displayed after Max Unread Messages value is exceeded.  I'm sending msgs at 1 second intervals but get the Queue is full msg right away.  I changed Max Unread Messages to 10, and there are no messages for 10 seconds; then (!)Queue is full msgs resume in console.  Curious that the msgs aren't being displayed in the console until after Max is exceeded?  I'm using your example code, but modified as below:
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class MyMessageListener : MonoBehaviour
{
    // Use this for initialization
    int obstacleDetected = 0;
    void Start()
    {
    }
    // Update is called once per frame
    void Update()
    {
       // transform.Rotate(1, 0, 0);
        if (obstacleDetected == 1)
        {
            transform.Rotate(20, 0, 0);
            obstacleDetected = 0;
        }
    }
    // Invoked when a line of data is received from the serial device.
    void OnMessageArrived(string msg)
    {
        Debug.Log("Arrived: " + msg);
        if (msg == "Obstacle Detected!")
        {
            obstacleDetected = 1;
        }
        Debug.Log(obstacleDetected);
    }
// Invoked when a connect/disconnect event occurs. The parameter 'success'
// will be 'true' upon connection, and 'false' upon disconnection or
// failure to connect.
void OnConnectionEvent(bool success)
    {
        Debug.Log(success ? "Device connected" : "Device disconnected");
    }
}
```
When I unrem the transform.Rotate line the cube spins on every Update, so that works.....
Oh, and my Arduino code (I cut and pasted the "Obstacle Detected!" message from Arduino IDE into Visual Studio to assure no typos (o:)  and using println to assure carriage return sent......

```c#
int isObstaclePin = 2;
int isObstacle = HIGH;
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(isObstaclePin, INPUT);
  Serial.begin(9600);
}
void loop() {
  isObstacle = digitalRead(isObstaclePin);
  if (isObstacle == LOW)
  {
    digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
    Serial.println("Obstacle Detected!");
  }
  else
  {Serial.println("All Clear!");
   digitalWrite(LED_BUILTIN, LOW);
  }
  delay(1000);
}
```
I saw the drop old msg post, but I don't know how to use it; but at only one msg per second, I didn't think that would be necessary, as the code grabs out of the buffer at a much faster rate?
What am I missing? 
Thx so much for Ardity and your time!

**Comment by dwilches** [comment]
Hello,
Thanks for using Ardity!

To confirm I understand correctly, in the case of "Max Unread Messages = 10" it takes 10 seconds to display this message: "Debug.Log("Arrived: " + msg);". Is that correct? Or this message is never being printed and instead you are just seeing the "Queue is full" message after 10 seconds?

Also, could you send me an image of this part of you console?
![image](https://user-images.githubusercontent.com/3975401/79824582-6e079d00-834b-11ea-8e25-4dd8750c415e.png)

I'm thinking you may have the "info" messages disabled.

Thanks.

**Comment by Dirk611** [comment]
Hi Daniel!
Thx for your quick response!  I'm a retired nuclear scientist that's played
with microcontrollers a lot, but historically have only used Windows or
Linux based systems occasionally....  Most of my art goes to Burning Man,
and although I have used laptops there, they really get trashed.  I
stumbled across a used Intel NUC (looks quite hardened and survivable), and
when I saw the power of Unity I think I just got converted (o:

Ah!  But to answer your question, no; actually what is happening is that
"Debug.Log("Arrived: " + msg);" doesn't get displayed, but the messages
sent from the Arduino, "All Clear!" and "Obstacle Detected!" get displayed
in the console.  But those messages are prefaced with a timestamp in
brackets and "Queue is full.  Dropping message:" then the Arduino message,
and followed with:  Unity.Debug:LogWarning(Object)
But nothing is displayed in the console until after the Max Unread Messages
value is exceeded, as near as I can tell.   "Debug.Log("Arrived: " + msg);"
never does get displayed, just what comes in the com port......
Cheers!
Dirk

P.S.  Thanks for the note in your pdf How To.... I hit the problem of using
the limited .NET 2.0 version right away with the com port (o:  Looks like
every time I want to use Unity with a com port I have to change the project
settings?  There must be a way to set the default to .NET 4.x?

PPS.  When I downloaded Ardity from the asset store, it's obviously stored
locally on my machine.  When starting a new project, I haven't been able to
figure out how to add it to my new project without having to go back to the
Asset Store and get it from there again.  I looked in the "Import New
Package" and "Import Package/Custom Package" under the Assets menu but I
guess I'm blind.  Or does one go back to the Asset Store on each new
project?  Thx!

**Comment by Dirk611** [comment]
Oops forgot to send you this:
[image: image.png]

**Comment by dwilches** [comment]
I can't see the image, did you attach it through GitHub's interface?

--
Daniel Wilches

**Comment by Dirk611** [comment]
Apologies; I'm also a Github newbie; I attached it to my gmail response.  This is a drag and drop to Github.  Thanks for your patience with me....
![Untitled](https://user-images.githubusercontent.com/11400732/79906041-fd549500-83cb-11ea-91a8-c94b415de05c.png)

**Comment by dwilches** [comment]
Could you change this line:
Debug.Log("Arrived: " + msg)

To this:
Debug.LogWarning("Arrived: " + msg)

I'm thinking something in your Unity is not logging normal messages, but
only warnings and errors.
So let's try that please.

--
Daniel Wilches

**Comment by Dirk611** [comment]
Thx for your help!  I tried that, and it didn't make any difference.   But you are right, regular Debug messages aren't getting displayed, only errors.  So I created a new project and am able to display Debug msgs just fine.  
BUT, then I noticed within the Visual Studio script, three dots underneath the methods OnMessageArrived and OnConnectionEvent.  Upon hovering my cursor over those, I get an explanation, as you can see in the screen clip below.  Does that have anything to do with it?  Did I somehow damage something that calls those routines in the first place?  (o:  Cheers!
![unused method](https://user-images.githubusercontent.com/11400732/79911217-dd759f00-83d4-11ea-8d75-1d9e97b695c9.png)

**Comment by dwilches** [comment]
Ah, did you set this MonoBehaviour as the listenr of the SerialController?
![image](https://user-images.githubusercontent.com/3975401/79929838-d1510800-83fb-11ea-85db-72d25f0cda18.png)

**Comment by dwilches** [comment]
This is how it should look like when correctly configured, notice there are both a SerialController and MessageListener in the same GameObject:

![image](https://user-images.githubusercontent.com/3975401/79929965-24c35600-83fc-11ea-9d20-01b6fd10c9fa.png)

**Comment by Dirk611** [comment]
Ah!  I'm sure that's what I have wrong.  And I see (above) and also, now, in your pdf instructions, 
Now set the “Message Listener” field to the GameObject that contains
the “MyMessageListener” script:
But, sorry for my stupidness, but I can't figure out how to do that.  I've deleted my objects, and re-added the SerialController prefab, as well as tried to do it with a Cube asset several ways, but can't seem to figure out how to "set" the "Message Listener" field to "MyMessageListener" (o:  I continue to end up with "None (Game Object)" in the Message Listener field and the MyMessageListener script getting added below it....  (puzzled emoji here (o:)
Please describe how I can "set" that field.  Thanks for your help!

**Comment by dwilches** [comment]
You can drag and drop the object from the hierarchy panel to the  "Message Listener". Or also you can use the little circle next to the Message Listener to select the object you want to put there.

**Comment by HitenderOswal** [comment]
thanks chat
