### ISSUE TITLE
Using the input from the Arduino to controll GameObject

### ISSUE THREAD

**Issue by Iriemonkey** [dwilches/Ardity#41]
Hello,

i am fairly new to working with Arduino and Unity, and i don't really understand how i can use the input from the Arduino to control "stuff" ( movement of a Game Object for example ).
I can print messages to the console in Unity by pressing a pushbutton on an Arduino circuit, but how do i use these messages to trigger something? (" e.g. save the value to a variable and move a cube, when the value is "1" .... i hope you get the point :/ )

Thank you in advance!
kind regards,
Tobi

**Comment by dwilches** [comment]
Hello,

Search around for how to move objects in Unity, then you can put that code inside of the methods that Ardity is executing.

For example, if you follow [this guide](https://github.com/dwilches/Ardity/blob/master/UnityProject/Ardity%20-%20Setup%20Guide.pdf) try putting the following code inside of the method `OnMessageArrived`:

    transform.Translate(Vector3.forward * Time.deltaTime);

Moreover, that parameter `msg` you see in the method `OnMessageArrived` can be used to move the object in different directions, just add an `if` and depending what the `msg` contains you can do:

    transform.Translate(Vector3.forward * Time.deltaTime);

or:

    transform.Translate(Vector3.back * Time.deltaTime);

Regards.
