### ISSUE TITLE
Can we use it to make a Bluetooth connection between HC-05 and Unity? 

### ISSUE THREAD

**Issue by ghost** [dwilches/Ardity#42]
Hello and thanks for this great package 
I just want to know if we could use it to translate the data using the Bluetooth chip instead of the serial wire 
Thanks.

**Comment by dwilches** [comment]
Hello!
Thanks for using Ardity.

You can use Ardity to connect with any device that can be manipulated through a serial port, including bluetooth devices.

Search around for how to expose your particular Bluetooth device as a virtual COM port, and then use Ardity to connect to that virtual COM port.

Hope this helps,
Regards.

**Comment by ghost** [comment]
I think that would work
Thanks for fast responding 
I'm gonna close this issue because I think that solution will solve my problem
