### ISSUE TITLE
Arduino Uno Wifi Rev2  does not connect with Unity

### ISSUE THREAD

**Issue by LiekeUnity** [dwilches/Ardity#46]
I have a question using Ardity with an Arduino Uno Wifi Rev2. I'm using the sample scenes provided in the package.

I tested Ardity with an Arduino Uno and it works perfectly fine. However, when I use the Uno Wifi Rev2 it does not work.

When I send a character from Unity to the Arduino, the Arduino does receive something (RX blinks). However, the action (in my case put a light on) does not work.

It seems like my Adruino is not able to read the serial message from Unity and it also does not send information to unity.

Does anyone else has experienced this problem? Or is it possible that the Serial Port of the Uno Wifi Rev2 does not open for Unity? The Arduino code works without using Unity.

Hope someone can help!
Regards

**Comment by dwilches** [comment]
Hello,
Some users have reported needing to enable DtsEnable and RtsEnable for their devices to work.
Check the bottom of the [README ](https://github.com/dwilches/Ardity) on information about how to enable those options.
Hope this helps

**Comment by LiekeUnity** [comment]
Hi, thanks for your response, this works perfectly!
