### ISSUE TITLE
DtrEnable required for some devices

### ISSUE THREAD

**Issue by dracolytch** [dwilches/Ardity#47]
Hey there,

Just playing around with your project, seems to work well! There was only one gotcha (which I found with other libraries, so it was no big deal to adjust for my use case).

For some devices, such as the AdaFruit Trinket M0 (And similar CircuitPython devices, I think) 

Adding the line:
serialPort.DtrEnable = true;

just before
serialPort.Open();

in AbstractSerialThread fixed the issue. However, I'm sure others would want to set through a constructor or similar.

**Comment by dwilches** [comment]
Hello,
Thank you for taking the time to report this.
Some other users have also reported the same, so I just updated the readme with some information.
Regards.

**Comment by dustinkerstein** [comment]
And for me, adding serialPort.RtsEnable = true broke communication. For my Arduino Nano, only DtrEnable was necessary.
