### ISSUE TITLE
How can I send numbers and variables to my arduino?

### ISSUE THREAD

**Issue by timeylies** [dwilches/Ardity#50]
Here is the script:
/**
 * Ardity (Serial Communication for Arduino + Unity)
 * Author: Daniel Wilches <dwilches@gmail.com>
 *
 * This work is released under the Creative Commons Attributions license.
 * https://creativecommons.org/licenses/by/2.0/
 */

using UnityEngine;
using System.Collections;
using UnityEditor;

/**
 * Sample for reading using polling by yourself, and writing too.
 */
public class SampleUserPolling_ReadWrite : MonoBehaviour
{
    public SerialController serialController;
    public string speed;
    

    // Initialization
    void Start()
    {
        serialController = GameObject.Find("SerialController").GetComponent<SerialController>();

        
    }

    // Executed each frame
    void Update()
    {
        

        //---------------------------------------------------------------------
        // Send data
        //---------------------------------------------------------------------

        speed = Car_Controller.speed1.ToString("D5");
        serialController.SendSerialMessage(speed);
        

       

        //---------------------------------------------------------------------
        // Receive data
        //---------------------------------------------------------------------

        string message = serialController.ReadSerialMessage();

        if(message == "P")
        {
            EditorApplication.isPlaying = false;
        }

        if (message == null)
            return;

        // Check if the message is plain data or a connect/disconnect event.
        if (ReferenceEquals(message, SerialController.SERIAL_DEVICE_CONNECTED))
            Debug.Log("Connection established");
        else if (ReferenceEquals(message, SerialController.SERIAL_DEVICE_DISCONNECTED))
            Debug.Log("Connection attempt failed or disconnection detected");
        else
            Debug.Log("Message arrived: " + message);
    }
}

Im trying to send my car speed to my arduino so it can display it to a lcd

**Comment by dwilches** [comment]
Hello,

On the receiving end, your numbers will be strings, so you need to find out how to convert a string to a number in C#. That's not specific to Ardity, but C#, look for a method that mentions "parsing" a string as a number. StackOverflow is a good place to find an answer to this.

Regards.
