### ISSUE TITLE
serialPort.DtrEnablerequired for Circuit Python on Circuit Playground

### ISSUE THREAD

**Issue by notaquestion** [dwilches/Ardity#53]
I'm using a Adafruit Circuit Playground Express with Circuit Python to write to the serial monitor. 

After some experimentation, I've discovered I need the following in AttemptConnection in Abstract Serial thread to make things work.
serialPort.DtrEnable = true;

I put it right after 
serialPort.Open();

I realize this is a pretty unique edge case. I don't know what the consequences of having this set to true on a normal Arduino would be. Buuuut... I really had to search to find where to put this/what was going on, so it might be cool to have a toggle somewhere?

(This is my first "issue", please let me know if this isn't the write place for this kind of thing? ty!)

**Comment by dwilches** [comment]
Hello,

Thanks for taking the time to report a workaround.
Actually that one is among the known issues people can face, and it's documented in the "readme":
https://github.com/dwilches/Ardity#communication-with-some-devices-doesnt-work-out-of-the-box

Thanks, regards.
