### ISSUE TITLE
Works In Editor but now on windows build

### ISSUE THREAD

**Issue by DevSpur** [dwilches/Ardity#56]
Hi Thanks for an awesome project, Im have an issues where in the editor it works as expected but as soon as I build it to run on windows it does not want to connect to my device (Im using esp32). I don't know if Im missing something. Ive used the example project and I only changed the baud rate to 115200 and the port name matches the Arduino editor.

**Comment by dwilches** [comment]
Hello!

Is there any exception being printed in the logs?

Regards.

**Comment by DevSpur** [comment]
Hi thanks for the reply 

I got it working I had the "scripting backend" set to IL2CPP instead of Mono.

**Comment by dwilches** [comment]
Thanks, I've added this information to the Common Issues in the Readme.
