### ISSUE TITLE
Working with BLE and Mobile 

### ISSUE THREAD

**Issue by jumoyang-dev** [dwilches/Ardity#58]
Hello,
I was wondering if Ardity can work with esp32 BLE & Unity Built on Mobile (IOS/Android). For example, if managed to get the baud rate and COM port of the device will it connect on the mobile device too?

**Comment by dwilches** [comment]
Hi
I can't tell you about that specific chip, but people have had success using Ardity with bluetooth devices and also with Android, so you'll need to give it a try.
Regards.

**Comment by paulks-software** [comment]
Can anybody confirm that it is working?

**Comment by emrecandegis** [comment]
i am working on three days.I can read usb serial port data. Although i can access sended data on bluetooth in putty, i cant still read from unity >.<
