### ISSUE TITLE
Sending hexadecimal values

### ISSUE THREAD

**Issue by Meryemamr** [dwilches/Ardity#6]
Hi, 
firt of all thank you for this package it was verry helpfull. but i have a problem to figure out how to send a hexadecimal data (byte[]) i added this method to your code :
public static byte[] HexStringToByteArray(string hexString)
	{
		
		byte[] result = new byte[hexString.Length / 2];

		for (int i = 0; i < hexString.Length; i += 2)
		{
			result[i / 2] = Convert.ToByte(hexString.Substring(i, 2), 16); // base 16
		}

		return result;
	}
if (Input.GetKeyDown (KeyCode.I)) {
			Debug.Log ("Initializing camera . . .");
			string hexString = "88010001FF";
			byte[] byteArray = HexStringToByteArray (hexString);
			serialController.SendSerialMessage (byteArray);

		}
i have this error :  Error CS1502: The method 'SerialController.SendSerialMessage(string)' has non valid arguments  
 Error CS1503: Argument 1 : impossible to convert 'byte[]' en 'string' (CS1503) (Assembly-CSharp)
Any idea how to fix this,i'll be verry appriciatif !
thanck's in advance!

**Comment by dwilches** [comment]
Hi,

The reason of the error is that function expects a `String` as its argument, not a `byte[]`.
I've been thinking of expanding the library to support arbitrary data to be sent/received. I think I can make this improvement now and you could use it when it's ready.

Could you tell me in your case how do you need to mark the end of your messages? are all of them of a fixed size or do they have a special delimiter at the end?

**Comment by Meryemamr** [comment]
Hi,

The structure of the packet (3 to 16 bytes) ,the message (1 to 14 bytes),
It's delimiter it's FF in hexadecimal.
Help...
Thank you!

**Comment by Meryemamr** [comment]
Helloo.....

**Comment by dwilches** [comment]
Hello Meryemamr,

Please check the latest version of the library, now it supports custom delimiters.

I added an Arduino sample and a new Unity scene that shows how the new code is used. In both of them, I set the delimiter to `255` (`0xFF`).

Please let me know if it works well!
Regards.

**Comment by Meryemamr** [comment]
Hello,
Thank you a lot,I did my tests the writing works well but i don't figure out how to
read from my camera ,i don't see the messages ,did i miss a thing??
thank's again,really appreciate your help!

**Comment by dwilches** [comment]
Since I don't know about your implementation I can only guess: are you sure you are using the same char terminator that your camera is expecting? Have you a way to debug what messages your camera is receiving? Maybe your camera expects first some initialization commands and won't talk to you until you send them?
