### ISSUE TITLE
The Data is visible in Arduino serial monitor but not reciving in Unity3D

### ISSUE THREAD

**Issue by DhavalKesaria1903** [dwilches/Ardity#60]
I am trying read the data from the RFID reder. The data is visible in the Arduino Serial Monitor but it is not getting recived in Unity editor for some reason. The other hardware like rotator is working fine. But with same code if I am trying to recieved data for the RFID it is not receiving in Unity. Can you please quickly hlep me here?

**Comment by macyk** [comment]
In the AbstractSerialThread class, remove the comments for line 196:

```
serialPort.DtrEnable = true;
serialPort.RtsEnable = true;
```

[https://github.com/dwilches/Ardity/issues/45](url)
