### ISSUE TITLE
Game crashes when exiting

### ISSUE THREAD

**Issue by callums005** [dwilches/Ardity#62]
Unity crashes any time I exit the game when the SerialController.cs script is in the scene. I have made sure that the COM port is the same, as well as the baud rate. When the game is playing it does not receive any messages from the Arduino, however, it will display a successful connection message. **Note that the unity project is new, and only has the Ardity package installed, alongside the SampleMessageListener.cs script (with printing within the functions)**.

Unity Version: 2021.2.19f1

**Comment by dwilches** [comment]
Hello,
Could you share more information about what error you see, which code you wrote and maybe even the project you are working on?

**Comment by callums005** [comment]
> Hello, Could you share more information about what error you see, which code you wrote and maybe even the project you are working on?

There is no error, Unity just freezes and has to be terminated via the task manager.
