### ISSUE TITLE
cant find the COM

### ISSUE THREAD

**Issue by MichauCorp** [dwilches/Ardity#63]
hello again.

I am currently trying to use ardity with the oculus quest 2 and I have been having some trouble figuring it out.
My current problem is that i cannot find any information regarding the device's serial ports, and i was hoping you can shed some insight on this/notify if there is a way to auto select an available serial port.

so far i would also like to add that ardity has been extremely helpful for me, and either way I give you my appreciation.

**Comment by dwilches** [comment]
Hello,
I'm glad Ardity is being helpful for you!

Regarding the Oculus ports, it depends on them what COM ports they make
available, so I'd suggest to look at their docs or ask them directly.

I've not worked with that device so I'm sorry I can't be of more help.

Regards.

**Comment by MichauCorp** [comment]
ok, thx anyway!
