### ISSUE TITLE
PortMapper trial

### ISSUE THREAD

**Issue by MichauCorp** [dwilches/Ardity#64]
hello the third.

i am currently trying to create a "port mapper" with ardity that is supposed to find the active serialport.
however my attempts so far have failed and i was hoping you might have some insights as to why/suggestions for a better method.

this is my current script (couldn't paste it as code sry):

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO.Ports;
using System.Threading.Tasks;

public class PortMapper3 : MonoBehaviour
{
    bool connected = false;
    private string name1 = "empty", messege = "";
    public SerialController controller;
    // Start is called before the first frame update
    void Start()
    {
        controller = GameObject.Find("SerialController").GetComponent<SerialController>();
        controller.enabled = false;
    }

    void Update()
    {
        if(!connected)
        {
            foreach(string s in SerialPort.GetPortNames())
            {
                controller.portName = s;
                controller.enabled = true;
                messege += controller.ReadSerialMessage();
                if (messege != "")
                {
                    name1 = s;
                    connected = true;
                }
                controller.enabled = false;
            }
            controller.portName = name1;
            Debug.Log(name1 + "," + messege);
        }
        else
        {
            if (controller.enabled == false)
                controller.enabled = true;
        }
    }

/////\\\\

I would prefer not using multiple controllers, however if you find it to be a fitting method then I will follow that advice

thanks for your time (again)

**Comment by dwilches** [comment]
Hello MichauCorp,

You mention your attempts have failed but didn't mention how it fails (is there an error message for example?).

Looking at the code, if you only want to find the first device that sends something over a COM port, then after `connected = true` you should be invoking `break` or your `for` would continue iterating.

That being said, notice here you are communicating with other devices you didn't intend to, like bluetooth headphones connected to that same computer, for example, so side-effects of opening arbitrary COM ports is something to consider.

Regards.

**Comment by MichauCorp** [comment]
to make an update on that, ive succeeded in making it using multiple serialcontrollers, the one that gets the correct messages isnt eliminated.
its rather messy but for now it works
