### ISSUE TITLE
Dropping too much messages when frame rate is below 100 fps

### ISSUE THREAD

**Issue by eraydurak35** [dwilches/Ardity#66]
when frame rate is below 100 fps ardity drops too many data because queue fills up quickly. Why its related to fps?

**Comment by dwilches** [comment]
Hello,
Some hyphoteses:
- you have code in OnUpdate that causes the Arduino to send data. And as OnUpdate is invoked each frame, then the higher the FPS, the higher the number of events you receive.
- because the FPS is so high, the machine gets busier and can't process messages coming from Arduino quick enough.
Regards

**Comment by dwilches** [comment]
Hello,
OnUpdate is executed on each frame, so the lower the fps, the fewer OnUpdate calls.
If you are reading messages from Arduino in OnUpdate, then fewer OnUpdate invocations means fewer events processed, so some will end being dropped when the queue fills.
Regards.

**Comment by eraydurak35** [comment]
I am not polling messages in Update() function. I am using OnMessageArrived() function to recieve data.  Sending 40 times ps inside FixedUpdate using serialController.SendSerialMessage(). Somehow OnMessageArrived() function doesnt trigger with every new data but every frame. Is there a way to trigger it on the background. Seperated from fps? like using FixedUpdate somewhere to trigger it 100 times ps?

**Comment by dwilches** [comment]
Hello,
You can change line 114 of the file SerialController.cs to use FixedUpdate instead of Update:
https://github.com/dwilches/Ardity/blob/master/UnityProject/Assets/Ardity/Scripts/SerialController.cs

Hope it helps.
