### ISSUE TITLE
Flooding queue when device is removed unexpectedly on linux

### ISSUE THREAD

**Issue by MNS26** [dwilches/Ardity#67]
![Screenshot_20230202_225407](https://user-images.githubusercontent.com/53867268/216458071-20d40313-9852-45d7-84d9-5c88df43c252.png)

when disconnecting out of nowhere it will flood the queue and nothing can be done about it other than restarting 

is it possible to fall back to checking for the serial device?

**Comment by dwilches** [comment]
Hi
Do you know what is the reason the device gets disconnected? That can give a hint at what is happening.
My guess is the device is not really disconnected, because otherwise there would be no messages arriving at the queue.

**Comment by MNS26** [comment]
i pressed the reset button because i had to change the code its running (RP2040), it has builtin usb

**Comment by MNS26** [comment]
![Screenshot_20230203_165131](https://user-images.githubusercontent.com/53867268/216647242-bbe19162-c0da-406a-a282-d63be71f5af7.png)
![Screenshot_20230203_171556](https://user-images.githubusercontent.com/53867268/216652772-db973594-6476-41ff-ae83-7940c8cd3b5c.png)


as shown in the picture the 1st reset made it show up (only sometimes needed) but after the 2nd reset it floods the queue

**Comment by MNS26** [comment]
@dwilches any thoughts on what to do?

**Comment by dwilches** [comment]
Hi
After a reset you won't be able to reuse the same connection, but you may be able to detect from Unity that the connection is broken and then close it and re-connect.
But I would only do this is pressing the reset button is a normal use-case of the application you are building, not if it's something that only happens during development.
