### ISSUE TITLE
A specific question

### ISSUE THREAD

**Issue by timurlenqs** [dwilches/Ardity#78]
I'm wondering, let's say a led is installed on pin 11 in arudino. 

We can already send messages to the pins with code from Unity, but what I actually want is that I want it to send messages to all pins first, I want it to determine which pin has what and which module is installed.

The 11th pin should show me the LED plugged in with debug and write that nothing is plugged in on the others. How can this be detected in arduino?

**Comment by dwilches** [comment]
Hello,

From Ardity you can send and receive any message to/from Arduino, but how those messages are interpreted on the Arduino side is specific to Ardunio, no Ardity involved at that point.

As that question is specific to Arduino, so you would get better answers in: https://arduino.stackexchange.com/

Regards.
